/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test2;

import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.geom.Rectangle2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author DarkT
 */
public class Interface extends javax.swing.JFrame{
    private static Core c = null;
    private int estado = 0;
    Point retanguloTopoEsquerdo = null;
    Point retanguloBaixoDireito = null;
    Point mousePonto;
    FrameAuxiliar frame;
    public void myInit(){
        try {
            if (c==null){
                c = new Core(this);
            }
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame = new FrameAuxiliar(this);
    }
    public void setMessage(String msg){
        this.lbInfo.setText(msg);
    }
    
    public void showFrameAuxiar(){
        frame.setVisible(true);
    }
    
    public void executarPlano(String pNome){
        frame.setVisible(false);
        c.test(pNome);
    }
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lbInfo.setText("INFo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lbInfo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_F){
            setMessage("estado : " + Integer.toString(estado));
            switch(estado){
                case 0 :
                    estado = 1;
                    mousePonto = MouseInfo.getPointerInfo().getLocation();
                    break;
                case 1 :
                    retanguloTopoEsquerdo = MouseInfo.getPointerInfo().getLocation();
                    estado = 2;
                    break;
                case 2 :
                    estado = 0;
                    retanguloBaixoDireito = MouseInfo.getPointerInfo().getLocation();
                    Rectangle ret = new Rectangle();
                    ret.x = retanguloTopoEsquerdo.x;
                    ret.y = retanguloTopoEsquerdo.y;
                    ret.height = Math.abs( retanguloTopoEsquerdo.y - retanguloBaixoDireito.y );
                    ret.width = Math.abs( retanguloTopoEsquerdo.x - retanguloBaixoDireito.x );
                    c.adicionarAction(mousePonto,ret);
                    break;
                default :
                    throw new UnsupportedOperationException("nue");
            }
        }else if (evt.getKeyCode()==KeyEvent.VK_I){
            showFrameAuxiar();
        }else if (evt.getKeyCode()==KeyEvent.VK_R){
            try {
                c.resetFile();
            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if (evt.getKeyCode()==KeyEvent.VK_X){
            //c.revalidarDadosNoDisco();
            System.exit(0);
        }else if (evt.getKeyCode()==KeyEvent.VK_Q){
            System.out.println("resetando estado para 0");
            estado = 0;
        }else{
            
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbInfo;
    // End of variables declaration//GEN-END:variables
}
